# sonsul 服务端口号
server:
  port: 8080
#注册名称
spring:
  application:
    name: consul-consumer-payment


  #consul注册中心地址
  cloud:
    consul:

      host: localhost  # windows运行单机版命令consul agent -dev
      port: 8500
      discovery:
       # hostname: 172.0.0.1
       service-name: ${spring.application.name}






  devtools:  #热部署自动化404问题
    restart:
      quiet-period: 2999ms
      poll-interval: 3000ms

