server:
  port: 8080
  # 服务别名 ---注册zookeeper到注册中心
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.0.113:2181  #docker 安装zookeeper


  devtools:  #热部署自动化404问题
    restart:
      quiet-period: 2999ms
      poll-interval: 3000ms
