server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848  # Nacos服务注册中心
    sentinel:
      transport:
        #配置Sentinel dashboard 地址

        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      datasource:  #添加nacos数据源配置
        ds1:
          nacos:
            server-addr: 192.168.0.101:8848
            dataId: ${spring.application.name}   #cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data_type: json
            rule_type: flow



management:
  endpoints:
    web:
      exposure:
        include: "*"
