server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据库类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql 驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  devtools:  #热部署自动化404问题
    restart:
      quiet-period: 2999ms
      poll-interval: 3000ms
  zipkin:
    base-url: http://192.168.0.106:9411   #docker run -d -p 9411:9411 openzipkin/zipkin
  sleuth:
    sampler:
      #采样率值介于0到1之间，1则表示全部采集
      probability: 1
eureka:
  client:
    #将自己注册到EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的的注册信息，默认为true。单节点无所谓，集群设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka  #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版注册
  instance:
    instance-id: payment8001 #actuator修改主机名称
    prefer-ip-address: true  #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1  #Eureka客户端向服务端发送心跳的时间间隔，单位为秒，默认为30s
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90s） ，超出时间剔除服务


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hm.springcloud.entities  # 所有Entity别名类所在包 后面的共同实体类包名称要一致
