server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:

      discovery:
        server-addr: 192.168.0.100:1111  #docker(3个nacos+mysql+ngnix) ,换成ngnix的1111端口，做集群

  #https://blog.csdn.net/BDawn/article/details/106234675
  #https://blog.csdn.net/qierkang/article/details/92657302

#打开端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
