server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #Eureka 服务器实例名称  host文件修改
  client:
    #false表示表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，职责就是维护服务，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务都需要这个依赖地址
      defaultZone: http://eureka7001.com:7001/eureka/   #单机版就自己
      #defaultZone: http://eureka7002.com:7002/eureka/   #关联7002集群版
  server:
    enable-self-preservation: false  # 关闭了Eureka的自我保护机制，保证不可用服务及时剔除
    eviction-interval-timer-in-ms: 2000  #监听心跳时间
