server: # 8004表示注册到zookeeper服务器的支付服务提供者端口号
  port: 8004
  # 服务别名 ---注册zookeeper到注册中心
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.0.113:2181  #docker 安装zookeeper
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据库类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql 驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  devtools:  #热部署自动化404问题
    restart:
      quiet-period: 2999ms
      poll-interval: 3000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hm.springcloud.entities  # 所有Entity别名类所在包 后面的共同实体类包名称要一致